### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by arianaa30** [Caoyichao/STCNet#1]
Interesting work. One thing I didn't understand about the architecture is, what exactly is the input to the Temporal and Spatial networks?
In this figure, the input to both networks appear the same (Residuals + RGB image), which shouldn't be the case because their focus is different.

![image](https://github.com/Caoyichao/STCNet/assets/5509837/913d0716-859a-4419-86da-7bdb073c736f)

**Comment by Caoyichao** [comment]
Thank you for your attention. In this network architecture diagram, the branch above is a **spatial branch**, and its input is **RGB frames**. The following branch is a **temporal branch**, and its input is a **residual branch**. Each branch only inputs one type of frame
